uploads = []
generated = []

[[outputs]]
id = "wAYwx44WR_qBjoNVrIbEt"
uri = "file://sprints/Conecta_SUS_Sprints.pdf"
type = "pdf"
title = "Conecta SUS - Documentação de Sprints (S1-S5)"

[[outputs]]
id = "x1OORR5WUQ94fzWJWEpgP"
uri = "file://sprints/Conecta_SUS_Sprints_Completo.pdf"
type = "pdf"
title = "Conecta SUS — Relatório Completo de Sprints (22 sprints)"
