// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sus-checkin/Escuro.tsx": () => import("../components/mockups/sus-checkin/Escuro.tsx"),
  "./components/mockups/sus-checkin/Limpo.tsx": () => import("../components/mockups/sus-checkin/Limpo.tsx"),
  "./components/mockups/sus-checkin/Vibrante.tsx": () => import("../components/mockups/sus-checkin/Vibrante.tsx")
};
